# SSHD Configuration Snippet for Port Hardening
# Path: /etc/ssh/sshd_config

# What ports, IPs and protocols we listen for
# Port 22
Port 2222

# AddressFamily any
# ListenAddress 0.0.0.0
# ListenAddress ::

# Authentication constraints
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no